### ISSUE TITLE
Brainweaver: change pvdb namespace to other

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ProjectRichelBilderbeek#166]
Suggest: `braw`, also rename filenames,

**Comment by janclod** [comment]
there are several variable names which contain the namespace pvdb. Do we need to change that? In the first place I thought to do a find&replace from pvdb:: to braw::

**Comment by richelbilderbeek** [comment]
If you dare: go ahead!

**Comment by richelbilderbeek** [comment]
This issue was moved to richelbilderbeek/Brainweaver#2
