### ISSUE TITLE
TestQtRoundedEditRect: changing focus pen width messes up the rectangle

### ISSUE THREAD

**Issue by janclod** [richelbilderbeek/ProjectRichelBilderbeek#254]
Launch TestTool:
* increase the contour pen width to 30
* give focus to the item
* change the focus pen width

Now the item will look really odd.
![bug](https://cloud.githubusercontent.com/assets/6673668/5738242/63c58f62-9bea-11e4-88c0-511343b3416e.png)

**Comment by richelbilderbeek** [comment]
I suggest that temporarily we assume contour and focus pens have equal widths, to first get a working concept map.
